repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: end-of-file-fixer
        stages: ["commit"]
  - repo: local
    hooks:
      - id: conventional-commit
        name: Conventional commit
        language: system
        entry: ./scripts/check_commit_msg.sh
        stages: ["commit-msg"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        name: Coding style linting
        stages: ["commit"]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        require_serial: true
        name: Coding style (Black)
        language_version: python3.11
        stages: ["commit"]
        exclude: ^legacy-backend.*$
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        require_serial: true
        name: isort
        args: ["--profile", "black"]
        exclude: ^legacy-backend.*$
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        require_serial: true
        name: Coding style (flake8)
        stages: ["commit"]
        exclude: ^legacy-backend.*$
