name: Pytest

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: crispy-api

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install -r requirements-dev.txt
      - run: pytest
