name: Run tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]

jobs:
  format:
    runs-on: ubuntu-latest
    name: Coding style
    steps:
      - uses: actions/checkout@v2
      - name: Run coding tests
        run: docker build . -f ./docker/yapf.Dockerfile -t crispy/yapf
      - name: Cleanup
        if: always()
        run: docker rmi -f $(docker images -f "dangling=true" -q) crispy/yapf || exit 0

  commit-style:
    runs-on: ubuntu-latest
    name: Commit style
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.3
